#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
urxvt &
firefox &
Spotify &
picom & 

$HOME/.config/polybar/launch.sh &

# Colors
. "$HOME/.cache/wal/colors.sh"
bspc monitor HDMI-2 -d internet dev terminal sys-status  
bspc monitor HDMI-1 -d A B C D E  

# This still remains broken.
#for monitor in $(bspc query -M); do 
#  bspc monitor $monitor -d 01 02 03 04 05 06 07 08 
#done 

bspc config border_width         3
bspc config window_gap          20

bspc config normal_border_color $color1 
bspc config active_border_color $color8
bspc config focused_border_color $color6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox  desktop='^6' state=floating
#bspc rule -a mplayer2 state=floating
bspc rule -a Spotify desktop='^1'
bspc rule -a urxvt desktop='^1'
bspc rule -a ranger desktop=^2 state=floating
#bspc rule -a Screenkey manage=off
#feh --bg-scale ~/Pictures/auocean.jpeg

#bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset


