#!/bin/sh
#
# ufetch-freebsd - tiny system info for freebsd

## INFO

# user is already defined
host="$(hostname)"
os="$(uname -sr)"
kernel="$(uname -iK)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages="$(pkg info | wc -l | sed -e 's/^[ \t]*//')"
shell="$(basename "${SHELL}")"

## UI DETECTION

parse_rcs() {
	for f in "${@}"; do
		wm="$(tail -n 1 "${f}" 2> /dev/null | cut -d ' ' -f 2)"
		[ -n "${wm}" ] && echo "${wm}" && return
	done
}

rcwm="$(parse_rcs "${HOME}/.xinitrc" "${HOME}/.xsession")"

ui='unknown'
uitype='UI'
if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
	ui="${XDG_CURRENT_DESKTOP}"
	uitype='DE'
elif [ -n "${DESKTOP_SESSION}" ]; then
	ui="${DESKTOP_SESSION}"
	uitype='DE'
elif [ -n "${rcwm}" ]; then
	ui="${rcwm}"
	uitype='WM'
elif [ -n "${XDG_SESSION_TYPE}" ]; then
	ui="${XDG_SESSION_TYPE}"
fi

ui="$(basename "${ui}")"

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput md)"
	black="$(tput AF 0)"
	red="$(tput AF 1)"
	green="$(tput AF 2)"
	yellow="$(tput AF 3)"
	blue="$(tput AF 4)"
	magenta="$(tput AF 5)"
	cyan="$(tput AF 6)"
	white="$(tput AF 7)"
	reset="$(tput me)"
fi

# you can change these
lc="${reset}${bold}${red}"          # labels
nc="${reset}${bold}${red}"          # user and hostname
ic="${reset}"                       # info
c0="${reset}${bold}${red}"          # first color
c1="${reset}${red}"                 # second color

## OUTPUT

cat <<EOF

${c0}   _  ${c1}_____  ${c0}_   ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}  / \\\`     \`/ \\  ${lc}OS:        ${ic}${os}${reset}
${c0}  \/       (__/  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c1}  |           |  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c1}  |           |  ${lc}PACKAGES:  ${ic}${packages}${reset}
${c1}   \         /   ${lc}SHELL:     ${ic}${shell}${reset}
${c1}    \`-_____-\`    ${lc}${uitype}:        ${ic}${ui}${reset}

EOF
